name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        path: main_repo

    - name: Checkout docs repo
      uses: actions/checkout@v4
      with:
        repository: xplainable/xplainable-docs
        token: ${{ secrets.DOCS_PUSH_TOKEN }}
        path: docs_repo

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        cd docs_repo/website
        pip install -r requirements.txt

    - name: Copy Examples to website working directory
      run: |
        cp -R main_repo/examples/* docs_repo/website/docs/tutorials

    - name: Run Conversion Script
      run: |
        cd docs_repo/website
        python convert_ipynb_to_mdx.py

    - name: Commit and Push Changes
      run: |
        cd docs_repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --cached --quiet && echo "No changes to commit" && exit 0
        git commit -m "Update tutorials from xplainable/xplainable examples"
        git push origin main
